import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "../styles/Home.module.css";
import { servicesFactory } from "@repo/ui/serviceFactory";
import { useQuery } from "react-query";
import { getProductList } from "@repo/ui/products";

const inter = Inter({ subsets: ["latin"] });
const kpService = servicesFactory.serviceType.enums.services.kpService;
const payload = {
  IsFeatured: true,
  IsNew: true,
};
export default function Home() {
  const { data } = useQuery({
    queryKey: "FeaturedList",
    queryFn: async () => {
      const data = await getProductList(kpService, payload);
      return data;
    },
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {data?.map((product: any) => {
          return <h1 key={product.ProductId}>{product.ProductName}</h1>;
        })}
      </main>
    </>
  );
}
